### ISSUE TITLE
Login requirements

### ISSUE THREAD

**Issue by toqueteos** [PistonDevelopers/hematite_server#8]
Login requires the following packets:
- [x] ClientChangeGameState
- [x] ClientChunkData (manual impl + requires Chunk and ChunkColumn data types) #32
- [x] ClientJoinGame
- [x] ClientKeepAlive
- [x] ClientPlayerAbilities
- [x] ClientPlayerPositionAndLook
- [x] ClientPluginMessage (manual impl) #23
- [x] ClientSpawnPosition
- [x] ClientTimeUpdate
- [x] ClientWindowItems (requires dealing with `Arr<i16, Slot>` + Slot data type) #22
- [x] Handshake
- [x] LoginSetCompression
- [x] LoginStart
- [x] LoginSuccess
- [x] ServerClientSettings
# Quirks

`Arr<K, V>` notation means array with K as length prefix and K-items of type V.

**Auth.** Only `online-mode=false`. No encryption or player validation. Fixing this would require using two crates: `rust-crypto` and `hyper` (or any other http client library, [curl](https://crates.io/crates/curl) would do it).

**Compression.** If we use disabled compression (LoginSetCompression) then we are almost ready to go. If not, then we need to use the `flate` crate.

**Chat.** It would be a great thing if we sorted out ClientChatMessage (not in previous list), which requires Chat data type (not that easy to handle), so players are greeted when they join and other players are notified when someone has just joined or left.

**Comment by toqueteos** [comment]
~~We are almost ready for this, currently on hold by #15.~~

**Comment by toqueteos** [comment]
Just `ClientChunkData` left, `ClientPluginMessage` proposal is already sent (#23).

**Comment by toqueteos** [comment]
All required packets are available, we can start working on this now.

**Comment by toqueteos** [comment]
Closing as #40 just got merged.
